//! Widget System for Continuum Studio
//!
//! Modular UI components that communicate via events.
//! Each widget is independent and can be composed into layouts.

pub mod diagram;
pub mod code_view;
pub mod terminal;
pub mod tab_bar;

use eframe::egui::Ui;
use anyhow::Result;

// Re-exports
pub use diagram::{DiagramWidget, DiagramNode, DiagramEdge, NodeShape, NodeStatus, ArrowType, DiagramTheme};
pub use code_view::{CodeViewWidget, CodeTheme, Language};
pub use terminal::{TerminalWidget, TerminalTheme, AnsiColor, TerminalLine};
pub use tab_bar::{TabBarWidget, TabBarTheme, Tab, TabType};

/// Core widget trait - all widgets implement this
pub trait Widget {
    /// Render the widget UI
    fn ui(&mut self, ui: &mut Ui) -> Result<Vec<WidgetEvent>>;
    
    /// Get the widget's display title
    fn title(&self) -> String;
    
    /// Get the widget's unique identifier
    fn id(&self) -> String;
}

/// Events generated by widgets for inter-widget communication
#[derive(Debug, Clone)]
pub enum WidgetEvent {
    /// No operation (placeholder)
    NoOp,
    
    /// Navigate to a file location
    NavigateTo {
        file: String,
        line: Option<usize>,
        column: Option<usize>,
    },
    
    /// Node selected in diagram
    DiagramNodeSelected(String),
    
    /// Node status changed
    DiagramNodeStatusChanged {
        node_id: String,
        status: NodeStatus,
    },
    
    /// Terminal command executed
    TerminalCommand(String),
    
    /// Terminal output received
    TerminalOutput(String),
    
    /// Code selection changed
    CodeSelectionChanged {
        file: String,
        start_line: usize,
        end_line: usize,
    },
    
    /// Request to open a new widget
    OpenWidget {
        widget_type: String,
        config: serde_json::Value,
    },
    
    /// Request to close this widget
    CloseWidget(String),
    
    /// Harness status update
    HarnessStatusUpdate {
        harness_id: String,
        status: String,
    },
    
    /// Agent message received
    AgentMessage {
        role: String,
        content: String,
    },
}

/// Manages multiple widgets and routes events between them
pub struct WidgetManager {
    event_queue: Vec<WidgetEvent>,
}

impl WidgetManager {
    pub fn new() -> Self {
        Self {
            event_queue: Vec::new(),
        }
    }

    /// Queue an event for processing
    pub fn queue_event(&mut self, event: WidgetEvent) {
        self.event_queue.push(event);
    }

    /// Process all queued events
    pub fn process_events(&mut self) -> Vec<WidgetEvent> {
        std::mem::take(&mut self.event_queue)
    }

    /// Check if there are pending events
    pub fn has_events(&self) -> bool {
        !self.event_queue.is_empty()
    }
}

impl Default for WidgetManager {
    fn default() -> Self {
        Self::new()
    }
}

/// Agent stream widget showing AI conversation
pub struct AgentStreamWidget {
    messages: Vec<AgentMessage>,
    max_messages: usize,
    auto_scroll: bool,
    frame_count: u64,
}

#[derive(Debug, Clone)]
pub struct AgentMessage {
    pub role: String,
    pub content: String,
    pub timestamp: chrono::DateTime<chrono::Utc>,
    pub source: Option<String>,  // Harness ID
    pub color: Option<String>,   // Color for visual identification
}

impl AgentStreamWidget {
    pub fn new() -> Self {
        Self {
            messages: Vec::new(),
            max_messages: 1000,
            auto_scroll: true,
            frame_count: 0,
        }
    }

    pub fn add_message(&mut self, role: impl Into<String>, content: impl Into<String>) {
        self.messages.push(AgentMessage {
            role: role.into(),
            content: content.into(),
            timestamp: chrono::Utc::now(),
            source: None,
            color: None,
        });
        
        // Trim old messages
        while self.messages.len() > self.max_messages {
            self.messages.remove(0);
        }
    }

    pub fn add_message_with_source(&mut self, role: impl Into<String>, content: impl Into<String>, source: Option<&str>) {
        self.messages.push(AgentMessage {
            role: role.into(),
            content: content.into(),
            timestamp: chrono::Utc::now(),
            source: source.map(String::from),
            color: None,  // Color will be looked up from harness registry
        });
        
        // Trim old messages
        while self.messages.len() > self.max_messages {
            self.messages.remove(0);
        }
    }

    pub fn append_to_last(&mut self, content: &str) {
        if let Some(last) = self.messages.last_mut() {
            last.content.push_str(content);
        } else {
            // No previous message, create new one
            self.add_message("assistant", content);
        }
    }

    pub fn clear(&mut self) {
        self.messages.clear();
    }
}

impl Default for AgentStreamWidget {
    fn default() -> Self {
        Self::new()
    }
}

impl Widget for AgentStreamWidget {
    fn ui(&mut self, ui: &mut Ui) -> Result<Vec<WidgetEvent>> {
        self.frame_count += 1;
        
        // Simulate event bus activity for demo
        if self.frame_count % 180 == 0 {
            self.add_message("assistant", format!("Frame {} - Event bus working!", self.frame_count));
        }
        
        egui::ScrollArea::vertical()
            .auto_shrink([false, false])
            .stick_to_bottom(self.auto_scroll)
            .show(ui, |ui| {
                for msg in &self.messages {
                    ui.horizontal(|ui| {
                        let role_color = match msg.role.as_str() {
                            "user" => eframe::egui::Color32::from_rgb(86, 156, 214),
                            "assistant" => eframe::egui::Color32::from_rgb(78, 201, 176),
                            "system" => eframe::egui::Color32::from_rgb(206, 145, 120),
                            _ => eframe::egui::Color32::GRAY,
                        };
                        ui.colored_label(role_color, &format!("{}:", msg.role));
                        ui.label(&msg.content);
                    });
                }
            });
        
        Ok(vec![])
    }

    fn title(&self) -> String {
        "Agent Stream".to_string()
    }

    fn id(&self) -> String {
        "agent_stream".to_string()
    }
}

/// Harness panel showing available harnesses and their status with interactive controls
pub struct HarnessPanelWidget {
    harnesses: Vec<HarnessInfo>,
    expanded: std::collections::HashSet<String>,
    custom_modes: Vec<CustomMode>,
    active_mode: Option<String>,
}

#[derive(Debug, Clone)]
pub struct HarnessInfo {
    pub id: String,
    pub harness_type: String,
    pub name: String,
    pub custom_name: Option<String>,
    pub workspace: Option<String>,
    pub color: Option<String>,
    pub status: HarnessStatus,
    pub description: String,
    pub window_name: Option<String>,
    pub capabilities: Vec<String>,
    pub tooling: Vec<HarnessTool>,
    pub studio_enhanced: bool,
}

#[derive(Debug, Clone)]
pub struct HarnessTool {
    pub id: String,
    pub name: String,
    pub enabled: bool,
    pub description: String,
}

#[derive(Debug, Clone)]
pub struct CustomMode {
    pub name: String,
    pub harness_configs: std::collections::HashMap<String, HarnessModeConfig>,
}

#[derive(Debug, Clone)]
pub struct HarnessModeConfig {
    pub enabled_tools: std::collections::HashSet<String>,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum HarnessStatus {
    Stopped,
    Searching,
    Starting,
    Running,
    Paused,
    Error,
}

impl HarnessStatus {
    pub fn color(&self) -> eframe::egui::Color32 {
        match self {
            HarnessStatus::Stopped => eframe::egui::Color32::GRAY,
            HarnessStatus::Searching => eframe::egui::Color32::from_rgb(79, 193, 233),
            HarnessStatus::Starting => eframe::egui::Color32::YELLOW,
            HarnessStatus::Running => eframe::egui::Color32::from_rgb(59, 165, 93),
            HarnessStatus::Paused => eframe::egui::Color32::from_rgb(209, 154, 102),
            HarnessStatus::Error => eframe::egui::Color32::from_rgb(207, 102, 121),
        }
    }

    pub fn label(&self) -> &'static str {
        match self {
            HarnessStatus::Stopped => "stopped",
            HarnessStatus::Searching => "searching",
            HarnessStatus::Starting => "starting",
            HarnessStatus::Running => "running",
            HarnessStatus::Paused => "paused",
            HarnessStatus::Error => "error",
        }
    }

    pub fn icon(&self) -> &'static str {
        match self {
            HarnessStatus::Stopped => "⏹",
            HarnessStatus::Searching => "🔍",
            HarnessStatus::Starting => "⏳",
            HarnessStatus::Running => "▶",
            HarnessStatus::Paused => "⏸",
            HarnessStatus::Error => "⚠",
        }
    }
}

impl HarnessInfo {
    fn default_cursor() -> Self {
        Self {
            id: "cursor".to_string(),
            harness_type: "cursor".to_string(),
            name: "Cursor IDE".to_string(),
            custom_name: None,
            workspace: None,
            color: Some("#4EC9B0".to_string()),  // Default teal
            status: HarnessStatus::Stopped,
            description: "Control Cursor IDE via automation".to_string(),
            window_name: None,
            capabilities: vec![
                "type_text".to_string(),
                "send_keys".to_string(),
                "screenshot".to_string(),
                "open_file".to_string(),
                "run_command".to_string(),
            ],
            tooling: vec![
                HarnessTool {
                    id: "keyboard".to_string(),
                    name: "Keyboard Input".to_string(),
                    enabled: true,
                    description: "Type text and send key combinations".to_string(),
                },
                HarnessTool {
                    id: "screenshot".to_string(),
                    name: "Screenshot Capture".to_string(),
                    enabled: true,
                    description: "Capture window screenshots".to_string(),
                },
                HarnessTool {
                    id: "ocr".to_string(),
                    name: "OCR Text Recognition".to_string(),
                    enabled: false,
                    description: "Extract text from screenshots (requires tesseract)".to_string(),
                },
                HarnessTool {
                    id: "clipboard".to_string(),
                    name: "Clipboard Integration".to_string(),
                    enabled: true,
                    description: "Read/write clipboard content".to_string(),
                },
                HarnessTool {
                    id: "window_focus".to_string(),
                    name: "Window Management".to_string(),
                    enabled: true,
                    description: "Focus and manage windows".to_string(),
                },
            ],
            studio_enhanced: false,
        }
    }
}

impl HarnessPanelWidget {
    pub fn new() -> Self {
        Self {
            harnesses: vec![HarnessInfo::default_cursor()],
            expanded: std::collections::HashSet::new(),
            custom_modes: vec![
                CustomMode {
                    name: "Development".to_string(),
                    harness_configs: std::collections::HashMap::new(),
                },
                CustomMode {
                    name: "Minimal".to_string(),
                    harness_configs: std::collections::HashMap::new(),
                },
            ],
            active_mode: None,
        }
    }

    pub fn set_harness_status(&mut self, harness_id: &str, status: HarnessStatus) {
        if let Some(harness) = self.harnesses.iter_mut().find(|h| h.id == harness_id) {
            harness.status = status;
        }
    }

    pub fn update_harness(&mut self, harness_id: &str, window_name: Option<String>, status: HarnessStatus) {
        if let Some(harness) = self.harnesses.iter_mut().find(|h| h.id == harness_id) {
            harness.status = status;
            harness.window_name = window_name;
        }
    }

    pub fn set_studio_enhanced(&mut self, harness_id: &str, enhanced: bool) {
        if let Some(harness) = self.harnesses.iter_mut().find(|h| h.id == harness_id) {
            harness.studio_enhanced = enhanced;
        }
    }

    pub fn add_harness(&mut self, info: HarnessInfo) {
        // Don't add if already exists
        if !self.harnesses.iter().any(|h| h.id == info.id) {
            self.harnesses.push(info);
        }
    }

    pub fn register_harness(&mut self, id: &str, harness_type: &str) {
        if !self.harnesses.iter().any(|h| h.id == id) {
            let info = match harness_type {
                "cursor" => {
                    let mut info = HarnessInfo::default_cursor();
                    info.id = id.to_string();
                    info
                },
                _ => HarnessInfo {
                    id: id.to_string(),
                    harness_type: harness_type.to_string(),
                    name: format!("{} ({})", harness_type, id),
                    custom_name: None,
                    workspace: None,
                    color: None,
                    status: HarnessStatus::Starting,
                    description: format!("Auto-registered {} harness", harness_type),
                    window_name: None,
                    capabilities: vec![],
                    tooling: vec![],
                    studio_enhanced: false,
                },
            };
            self.harnesses.push(info);
        }
    }

    pub fn set_harness_color(&mut self, harness_id: &str, color: Option<String>) {
        if let Some(harness) = self.harnesses.iter_mut().find(|h| h.id == harness_id) {
            harness.color = color;
        }
    }

    pub fn set_harness_custom_name(&mut self, harness_id: &str, name: Option<String>) {
        if let Some(harness) = self.harnesses.iter_mut().find(|h| h.id == harness_id) {
            harness.custom_name = name;
        }
    }

    pub fn set_harness_workspace(&mut self, harness_id: &str, workspace: &str) {
        if let Some(harness) = self.harnesses.iter_mut().find(|h| h.id == harness_id) {
            harness.workspace = Some(workspace.to_string());
        }
    }

    pub fn set_harness_window(&mut self, harness_id: &str, window_name: &str) {
        if let Some(harness) = self.harnesses.iter_mut().find(|h| h.id == harness_id) {
            harness.window_name = Some(window_name.to_string());
        }
    }

    /// Update harness metadata from Synapsix
    pub fn set_harness_metadata(
        &mut self,
        harness_id: &str,
        custom_name: Option<String>,
        color: Option<String>,
        window_name: Option<String>,
        capabilities: Option<Vec<String>>,
        tooling: Option<Vec<(String, String, bool)>>,
        studio_enhanced: Option<bool>,
    ) {
        if let Some(harness) = self.harnesses.iter_mut().find(|h| h.id == harness_id) {
            if let Some(name) = custom_name {
                harness.custom_name = Some(name);
            }
            if let Some(c) = color {
                harness.color = Some(c);
            }
            if let Some(w) = window_name {
                harness.window_name = Some(w);
            }
            if let Some(caps) = capabilities {
                harness.capabilities = caps;
            }
            if let Some(tools) = tooling {
                harness.tooling = tools.into_iter().map(|(id, name, enabled)| {
                    HarnessTool {
                        id,
                        name: name.clone(),
                        enabled,
                        description: format!("{} tool", name),
                    }
                }).collect();
            }
            if let Some(enhanced) = studio_enhanced {
                harness.studio_enhanced = enhanced;
            }
        }
    }

    pub fn toggle_tool(&mut self, harness_id: &str, tool_id: &str) {
        if let Some(harness) = self.harnesses.iter_mut().find(|h| h.id == harness_id) {
            if let Some(tool) = harness.tooling.iter_mut().find(|t| t.id == tool_id) {
                tool.enabled = !tool.enabled;
            }
        }
    }

    fn render_harness_card(&mut self, ui: &mut Ui, index: usize) -> Vec<WidgetEvent> {
        let mut events = vec![];
        let harness = &self.harnesses[index];
        let harness_id = harness.id.clone();
        let is_expanded = self.expanded.contains(&harness_id);
        
        let frame = eframe::egui::Frame::none()
            .inner_margin(8.0)
            .rounding(4.0)
            .fill(eframe::egui::Color32::from_rgb(30, 30, 30));
        
        frame.show(ui, |ui| {
            // Header row
            ui.horizontal(|ui| {
                // Expand/collapse button
                let expand_text = if is_expanded { "▼" } else { "▶" };
                if ui.small_button(expand_text).clicked() {
                    if is_expanded {
                        self.expanded.remove(&harness_id);
                    } else {
                        self.expanded.insert(harness_id.clone());
                    }
                }
                
                // Status indicator with animation hint
                let status_color = harness.status.color();
                let (rect, _response) = ui.allocate_exact_size(
                    eframe::egui::Vec2::new(12.0, 12.0),
                    eframe::egui::Sense::hover(),
                );
                ui.painter().circle_filled(rect.center(), 5.0, status_color);
                
                // Name with studio enhancement indicator
                // Use custom_name if available, otherwise fall back to name
                let display_name = harness.custom_name.as_ref().unwrap_or(&harness.name);
                ui.label(eframe::egui::RichText::new(display_name).strong());
                
                if harness.studio_enhanced {
                    ui.colored_label(
                        eframe::egui::Color32::from_rgb(78, 201, 176),
                        "◈"
                    ).on_hover_text("Studio Enhanced - Extended features available");
                }
                
                ui.with_layout(eframe::egui::Layout::right_to_left(eframe::egui::Align::Center), |ui| {
                    // Status label
                    ui.colored_label(
                        status_color,
                        format!("{} {}", harness.status.icon(), harness.status.label()),
                    );
                });
            });
            
            // Window info if available
            if let Some(ref window_name) = harness.window_name {
                ui.horizontal(|ui| {
                    ui.add_space(20.0);
                    ui.colored_label(
                        eframe::egui::Color32::from_rgb(128, 128, 128),
                        format!("🪟 {}", window_name),
                    );
                });
            }
            
            // Expanded content
            if self.expanded.contains(&harness_id) {
                ui.add_space(8.0);
                ui.separator();
                ui.add_space(4.0);
                
                // Description
                ui.label(eframe::egui::RichText::new(&harness.description).italics().weak());
                
                ui.add_space(8.0);
                
                // Action buttons
                ui.horizontal(|ui| {
                    let can_start = matches!(harness.status, HarnessStatus::Stopped | HarnessStatus::Error);
                    let can_stop = matches!(harness.status, HarnessStatus::Running | HarnessStatus::Paused | HarnessStatus::Searching);
                    let is_running = harness.status == HarnessStatus::Running;
                    
                    ui.add_enabled_ui(can_start, |ui| {
                        if ui.button("▶ Start").clicked() {
                            events.push(WidgetEvent::HarnessStatusUpdate {
                                harness_id: harness_id.clone(),
                                status: "start".to_string(),
                            });
                        }
                    });
                    
                    ui.add_enabled_ui(can_stop, |ui| {
                        if ui.button("⏹ Stop").clicked() {
                            events.push(WidgetEvent::HarnessStatusUpdate {
                                harness_id: harness_id.clone(),
                                status: "stop".to_string(),
                            });
                        }
                    });
                    
                    ui.add_enabled_ui(is_running, |ui| {
                        if ui.button("📷 Screenshot").clicked() {
                            events.push(WidgetEvent::HarnessStatusUpdate {
                                harness_id: harness_id.clone(),
                                status: "screenshot".to_string(),
                            });
                        }
                    });
                    
                    if ui.button("🎯 Focus").clicked() {
                        events.push(WidgetEvent::HarnessStatusUpdate {
                            harness_id: harness_id.clone(),
                            status: "focus".to_string(),
                        });
                    }
                });
                
                ui.add_space(8.0);
                
                // Tooling toggles
                if !harness.tooling.is_empty() {
                    ui.label(eframe::egui::RichText::new("Tooling").strong().small());
                    ui.add_space(4.0);
                    
                    let tooling_snapshot: Vec<_> = harness.tooling.iter()
                        .map(|t| (t.id.clone(), t.name.clone(), t.enabled, t.description.clone()))
                        .collect();
                    
                    for (tool_id, tool_name, tool_enabled, tool_desc) in tooling_snapshot {
                        ui.horizontal(|ui| {
                            ui.add_space(10.0);
                            
                            let mut enabled = tool_enabled;
                            if ui.checkbox(&mut enabled, &tool_name).changed() {
                                // Toggle will be handled after the loop
                                events.push(WidgetEvent::HarnessStatusUpdate {
                                    harness_id: harness_id.clone(),
                                    status: format!("toggle_tool:{}", tool_id),
                                });
                            }
                            
                            ui.colored_label(
                                eframe::egui::Color32::from_rgb(100, 100, 100),
                                "ⓘ",
                            ).on_hover_text(&tool_desc);
                        });
                    }
                }
                
                // Capabilities
                if !harness.capabilities.is_empty() {
                    ui.add_space(8.0);
                    ui.label(eframe::egui::RichText::new("Capabilities").strong().small());
                    ui.horizontal_wrapped(|ui| {
                        for cap in &harness.capabilities {
                            ui.add(
                                eframe::egui::Label::new(
                                    eframe::egui::RichText::new(cap)
                                        .background_color(eframe::egui::Color32::from_rgb(60, 60, 60))
                                        .small()
                                )
                            );
                        }
                    });
                }
            }
        });
        
        events
    }
}

impl Default for HarnessPanelWidget {
    fn default() -> Self {
        Self::new()
    }
}

/// Cursor Orchestrator Widget - Multi-instance management
pub struct OrchestratorWidget {
    instances: Vec<CursorInstanceInfo>,
    show_launch_dialog: bool,
    selected_version: String,
    selected_workspace: String,
    resource_limits: ResourceLimits,
}

#[derive(Debug, Clone)]
pub struct CursorInstanceInfo {
    pub id: String,
    pub version: String,
    pub workspace: String,
    pub status: InstanceStatus,
    pub memory_mb: u64,
    pub uptime_seconds: u64,
    pub data_dir: String,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum InstanceStatus {
    Starting,
    Running,
    Stopped,
    Error,
}

impl InstanceStatus {
    pub fn color(&self) -> eframe::egui::Color32 {
        match self {
            InstanceStatus::Starting => eframe::egui::Color32::YELLOW,
            InstanceStatus::Running => eframe::egui::Color32::from_rgb(59, 165, 93),
            InstanceStatus::Stopped => eframe::egui::Color32::GRAY,
            InstanceStatus::Error => eframe::egui::Color32::from_rgb(207, 102, 121),
        }
    }

    pub fn label(&self) -> &'static str {
        match self {
            InstanceStatus::Starting => "starting",
            InstanceStatus::Running => "running",
            InstanceStatus::Stopped => "stopped",
            InstanceStatus::Error => "error",
        }
    }

    pub fn icon(&self) -> &'static str {
        match self {
            InstanceStatus::Starting => "⏳",
            InstanceStatus::Running => "▶",
            InstanceStatus::Stopped => "⏹",
            InstanceStatus::Error => "⚠",
        }
    }
}

#[derive(Debug, Clone)]
pub struct ResourceLimits {
    pub max_instances: usize,
    pub max_memory_mb: u64,
    pub memory_per_instance: u64,
}

impl Default for ResourceLimits {
    fn default() -> Self {
        Self {
            max_instances: 5,
            max_memory_mb: 16_000,
            memory_per_instance: 4_000,
        }
    }
}

impl OrchestratorWidget {
    pub fn new() -> Self {
        Self {
            instances: Vec::new(),
            show_launch_dialog: false,
            selected_version: "2.4.21".to_string(),
            selected_workspace: "default".to_string(),
            resource_limits: ResourceLimits::default(),
        }
    }

    pub fn add_instance(&mut self, info: CursorInstanceInfo) {
        self.instances.push(info);
    }

    pub fn update_instance_status(&mut self, id: &str, status: InstanceStatus) {
        if let Some(inst) = self.instances.iter_mut().find(|i| i.id == id) {
            inst.status = status;
        }
    }

    pub fn remove_instance(&mut self, id: &str) {
        self.instances.retain(|i| i.id != id);
    }

    pub fn update_instance_memory(&mut self, id: &str, memory_mb: u64) {
        if let Some(inst) = self.instances.iter_mut().find(|i| i.id == id) {
            inst.memory_mb = memory_mb;
        }
    }

    fn total_memory_usage(&self) -> u64 {
        self.instances.iter().map(|i| i.memory_mb).sum()
    }

    fn render_instance_card(&self, ui: &mut Ui, instance: &CursorInstanceInfo) -> Vec<WidgetEvent> {
        let mut events = vec![];

        let frame = eframe::egui::Frame::none()
            .inner_margin(8.0)
            .rounding(4.0)
            .fill(eframe::egui::Color32::from_rgb(35, 35, 40));

        frame.show(ui, |ui| {
            // Header row
            ui.horizontal(|ui| {
                // Status indicator
                let status_color = instance.status.color();
                let (rect, _) = ui.allocate_exact_size(
                    eframe::egui::Vec2::new(12.0, 12.0),
                    eframe::egui::Sense::hover(),
                );
                ui.painter().circle_filled(rect.center(), 5.0, status_color);

                // Version and workspace
                ui.label(eframe::egui::RichText::new(&format!("v{}", instance.version)).strong());
                ui.label(eframe::egui::RichText::new(&format!("({})", instance.workspace)).weak());

                ui.with_layout(eframe::egui::Layout::right_to_left(eframe::egui::Align::Center), |ui| {
                    ui.colored_label(
                        status_color,
                        format!("{} {}", instance.status.icon(), instance.status.label()),
                    );
                });
            });

            // Details row
            ui.horizontal(|ui| {
                ui.add_space(20.0);
                ui.colored_label(
                    eframe::egui::Color32::from_rgb(128, 128, 128),
                    format!("📊 {}MB  ⏱ {}m", instance.memory_mb, instance.uptime_seconds / 60),
                );
            });

            // Action buttons
            ui.add_space(4.0);
            ui.horizontal(|ui| {
                if instance.status == InstanceStatus::Running {
                    if ui.small_button("🎯 Focus").clicked() {
                        events.push(WidgetEvent::HarnessStatusUpdate {
                            harness_id: instance.id.clone(),
                            status: "focus".to_string(),
                        });
                    }
                    if ui.small_button("⏹ Stop").clicked() {
                        events.push(WidgetEvent::HarnessStatusUpdate {
                            harness_id: instance.id.clone(),
                            status: "stop".to_string(),
                        });
                    }
                } else if instance.status == InstanceStatus::Stopped {
                    if ui.small_button("▶ Start").clicked() {
                        events.push(WidgetEvent::HarnessStatusUpdate {
                            harness_id: instance.id.clone(),
                            status: "start".to_string(),
                        });
                    }
                }
                if ui.small_button("♻ Upgrade").clicked() {
                    events.push(WidgetEvent::HarnessStatusUpdate {
                        harness_id: instance.id.clone(),
                        status: "upgrade".to_string(),
                    });
                }
            });
        });

        events
    }
}

impl Default for OrchestratorWidget {
    fn default() -> Self {
        Self::new()
    }
}

impl Widget for OrchestratorWidget {
    fn ui(&mut self, ui: &mut Ui) -> Result<Vec<WidgetEvent>> {
        let mut all_events = vec![];

        // Header
        ui.horizontal(|ui| {
            ui.heading("🎯 Cursor Orchestrator");
            ui.with_layout(eframe::egui::Layout::right_to_left(eframe::egui::Align::Center), |ui| {
                if ui.button("+ Launch Instance").clicked() {
                    self.show_launch_dialog = true;
                }
            });
        });

        ui.separator();
        ui.add_space(8.0);

        // Resource summary
        let total_memory = self.total_memory_usage();
        let running_count = self.instances.iter().filter(|i| i.status == InstanceStatus::Running).count();

        ui.horizontal(|ui| {
            ui.label(format!(
                "📊 Instances: {}/{} | Memory: {}MB/{}MB",
                running_count,
                self.resource_limits.max_instances,
                total_memory,
                self.resource_limits.max_memory_mb
            ));
        });

        // Progress bar for memory
        ui.add(eframe::egui::ProgressBar::new(total_memory as f32 / self.resource_limits.max_memory_mb as f32)
            .text(format!("Memory: {}MB", total_memory)));

        ui.add_space(8.0);
        ui.separator();
        ui.add_space(8.0);

        // Instance list
        if self.instances.is_empty() {
            ui.vertical_centered(|ui| {
                ui.add_space(20.0);
                ui.label(eframe::egui::RichText::new("No Cursor instances running").weak());
                ui.add_space(10.0);
                ui.label("Click 'Launch Instance' to start a new Cursor");
                ui.add_space(20.0);
            });
        } else {
            egui::ScrollArea::vertical()
                .auto_shrink([false, false])
                .show(ui, |ui| {
                    let instances_snapshot: Vec<_> = self.instances.clone();
                    for instance in &instances_snapshot {
                        let events = self.render_instance_card(ui, instance);
                        all_events.extend(events);
                        ui.add_space(4.0);
                    }
                });
        }

        // Launch dialog
        if self.show_launch_dialog {
            egui::Window::new("Launch Cursor Instance")
                .collapsible(false)
                .resizable(false)
                .show(ui.ctx(), |ui| {
                    ui.horizontal(|ui| {
                        ui.label("Version:");
                        ui.text_edit_singleline(&mut self.selected_version);
                    });

                    ui.horizontal(|ui| {
                        ui.label("Workspace:");
                        ui.text_edit_singleline(&mut self.selected_workspace);
                    });

                    ui.add_space(8.0);

                    ui.horizontal(|ui| {
                        if ui.button("Launch").clicked() {
                            all_events.push(WidgetEvent::OpenWidget {
                                widget_type: "launch_cursor".to_string(),
                                config: serde_json::json!({
                                    "version": self.selected_version,
                                    "workspace": self.selected_workspace,
                                }),
                            });
                            self.show_launch_dialog = false;
                        }
                        if ui.button("Cancel").clicked() {
                            self.show_launch_dialog = false;
                        }
                    });
                });
        }

        Ok(all_events)
    }

    fn title(&self) -> String {
        "Cursor Orchestrator".to_string()
    }

    fn id(&self) -> String {
        "orchestrator".to_string()
    }
}

impl Widget for HarnessPanelWidget {
    fn ui(&mut self, ui: &mut Ui) -> Result<Vec<WidgetEvent>> {
        let mut all_events = vec![];
        
        // Header with mode selector
        ui.horizontal(|ui| {
            ui.label(eframe::egui::RichText::new("🎛 Harnesses").strong());
            ui.with_layout(eframe::egui::Layout::right_to_left(eframe::egui::Align::Center), |ui| {
                eframe::egui::ComboBox::from_id_salt("mode_selector")
                    .selected_text(self.active_mode.as_deref().unwrap_or("Default"))
                    .show_ui(ui, |ui| {
                        if ui.selectable_label(self.active_mode.is_none(), "Default").clicked() {
                            self.active_mode = None;
                        }
                        for mode in &self.custom_modes {
                            if ui.selectable_label(
                                self.active_mode.as_ref() == Some(&mode.name),
                                &mode.name
                            ).clicked() {
                                self.active_mode = Some(mode.name.clone());
                            }
                        }
                    });
                ui.label("Mode:");
            });
        });
        
        ui.add_space(8.0);
        ui.separator();
        ui.add_space(4.0);
        
        // Harness cards
        egui::ScrollArea::vertical()
            .auto_shrink([false, false])
            .show(ui, |ui| {
                let harness_count = self.harnesses.len();
                for i in 0..harness_count {
                    let events = self.render_harness_card(ui, i);
                    all_events.extend(events);
                    ui.add_space(4.0);
                }
                
                // Add harness button
                ui.add_space(8.0);
                if ui.button("+ Add Harness").clicked() {
                    // Would open a dialog to add new harness
                }
            });
        
        // Process tool toggle events
        for event in &all_events {
            if let WidgetEvent::HarnessStatusUpdate { harness_id, status } = event {
                if let Some(tool_id) = status.strip_prefix("toggle_tool:") {
                    self.toggle_tool(harness_id, tool_id);
                }
            }
        }
        
        Ok(all_events)
    }

    fn title(&self) -> String {
        "Harnesses".to_string()
    }

    fn id(&self) -> String {
        "harness_panel".to_string()
    }
}
