//! Widget System for Continuum Studio
//!
//! Modular UI components that communicate via events.
//! Each widget is independent and can be composed into layouts.

pub mod diagram;
pub mod code_view;
pub mod terminal;
pub mod tab_bar;

use eframe::egui::Ui;
use anyhow::Result;

// Re-exports
pub use diagram::{DiagramWidget, DiagramNode, DiagramEdge, NodeShape, NodeStatus, ArrowType, DiagramTheme};
pub use code_view::{CodeViewWidget, CodeTheme, Language};
pub use terminal::{TerminalWidget, TerminalTheme, AnsiColor, TerminalLine};
pub use tab_bar::{TabBarWidget, TabBarTheme, Tab, TabType};

/// Core widget trait - all widgets implement this
pub trait Widget {
    /// Render the widget UI
    fn ui(&mut self, ui: &mut Ui) -> Result<Vec<WidgetEvent>>;
    
    /// Get the widget's display title
    fn title(&self) -> String;
    
    /// Get the widget's unique identifier
    fn id(&self) -> String;
}

/// Events generated by widgets for inter-widget communication
#[derive(Debug, Clone)]
pub enum WidgetEvent {
    /// No operation (placeholder)
    NoOp,
    
    /// Navigate to a file location
    NavigateTo {
        file: String,
        line: Option<usize>,
        column: Option<usize>,
    },
    
    /// Node selected in diagram
    DiagramNodeSelected(String),
    
    /// Node status changed
    DiagramNodeStatusChanged {
        node_id: String,
        status: NodeStatus,
    },
    
    /// Terminal command executed
    TerminalCommand(String),
    
    /// Terminal output received
    TerminalOutput(String),
    
    /// Code selection changed
    CodeSelectionChanged {
        file: String,
        start_line: usize,
        end_line: usize,
    },
    
    /// Request to open a new widget
    OpenWidget {
        widget_type: String,
        config: serde_json::Value,
    },
    
    /// Request to close this widget
    CloseWidget(String),
    
    /// Harness status update
    HarnessStatusUpdate {
        harness_id: String,
        status: String,
    },
    
    /// Agent message received
    AgentMessage {
        role: String,
        content: String,
    },
}

/// Manages multiple widgets and routes events between them
pub struct WidgetManager {
    event_queue: Vec<WidgetEvent>,
}

impl WidgetManager {
    pub fn new() -> Self {
        Self {
            event_queue: Vec::new(),
        }
    }

    /// Queue an event for processing
    pub fn queue_event(&mut self, event: WidgetEvent) {
        self.event_queue.push(event);
    }

    /// Process all queued events
    pub fn process_events(&mut self) -> Vec<WidgetEvent> {
        std::mem::take(&mut self.event_queue)
    }

    /// Check if there are pending events
    pub fn has_events(&self) -> bool {
        !self.event_queue.is_empty()
    }
}

impl Default for WidgetManager {
    fn default() -> Self {
        Self::new()
    }
}

/// Agent stream widget showing AI conversation
pub struct AgentStreamWidget {
    messages: Vec<AgentMessage>,
    max_messages: usize,
    auto_scroll: bool,
    frame_count: u64,
}

#[derive(Debug, Clone)]
pub struct AgentMessage {
    pub role: String,
    pub content: String,
    pub timestamp: chrono::DateTime<chrono::Utc>,
}

impl AgentStreamWidget {
    pub fn new() -> Self {
        Self {
            messages: Vec::new(),
            max_messages: 1000,
            auto_scroll: true,
            frame_count: 0,
        }
    }

    pub fn add_message(&mut self, role: impl Into<String>, content: impl Into<String>) {
        self.messages.push(AgentMessage {
            role: role.into(),
            content: content.into(),
            timestamp: chrono::Utc::now(),
        });
        
        // Trim old messages
        while self.messages.len() > self.max_messages {
            self.messages.remove(0);
        }
    }

    pub fn clear(&mut self) {
        self.messages.clear();
    }
}

impl Default for AgentStreamWidget {
    fn default() -> Self {
        Self::new()
    }
}

impl Widget for AgentStreamWidget {
    fn ui(&mut self, ui: &mut Ui) -> Result<Vec<WidgetEvent>> {
        self.frame_count += 1;
        
        // Simulate event bus activity for demo
        if self.frame_count % 180 == 0 {
            self.add_message("assistant", format!("Frame {} - Event bus working!", self.frame_count));
        }
        
        egui::ScrollArea::vertical()
            .auto_shrink([false, false])
            .stick_to_bottom(self.auto_scroll)
            .show(ui, |ui| {
                for msg in &self.messages {
                    ui.horizontal(|ui| {
                        let role_color = match msg.role.as_str() {
                            "user" => eframe::egui::Color32::from_rgb(86, 156, 214),
                            "assistant" => eframe::egui::Color32::from_rgb(78, 201, 176),
                            "system" => eframe::egui::Color32::from_rgb(206, 145, 120),
                            _ => eframe::egui::Color32::GRAY,
                        };
                        ui.colored_label(role_color, &format!("{}:", msg.role));
                        ui.label(&msg.content);
                    });
                }
            });
        
        Ok(vec![])
    }

    fn title(&self) -> String {
        "Agent Stream".to_string()
    }

    fn id(&self) -> String {
        "agent_stream".to_string()
    }
}

/// Harness panel showing available harnesses and their status
pub struct HarnessPanelWidget {
    harnesses: Vec<HarnessInfo>,
}

#[derive(Debug, Clone)]
pub struct HarnessInfo {
    pub id: String,
    pub name: String,
    pub status: HarnessStatus,
    pub description: String,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum HarnessStatus {
    Stopped,
    Starting,
    Running,
    Paused,
    Error,
}

impl HarnessStatus {
    pub fn color(&self) -> eframe::egui::Color32 {
        match self {
            HarnessStatus::Stopped => eframe::egui::Color32::GRAY,
            HarnessStatus::Starting => eframe::egui::Color32::YELLOW,
            HarnessStatus::Running => eframe::egui::Color32::from_rgb(59, 165, 93),
            HarnessStatus::Paused => eframe::egui::Color32::from_rgb(209, 154, 102),
            HarnessStatus::Error => eframe::egui::Color32::from_rgb(207, 102, 121),
        }
    }

    pub fn label(&self) -> &'static str {
        match self {
            HarnessStatus::Stopped => "stopped",
            HarnessStatus::Starting => "starting",
            HarnessStatus::Running => "running",
            HarnessStatus::Paused => "paused",
            HarnessStatus::Error => "error",
        }
    }
}

impl HarnessPanelWidget {
    pub fn new() -> Self {
        // Initialize with default harnesses
        Self {
            harnesses: vec![
                HarnessInfo {
                    id: "cursor".to_string(),
                    name: "Cursor IDE".to_string(),
                    status: HarnessStatus::Stopped,
                    description: "Control Cursor IDE via automation".to_string(),
                },
                HarnessInfo {
                    id: "android_studio".to_string(),
                    name: "Android Studio".to_string(),
                    status: HarnessStatus::Stopped,
                    description: "Control Android Studio for mobile development".to_string(),
                },
                HarnessInfo {
                    id: "godot".to_string(),
                    name: "Godot".to_string(),
                    status: HarnessStatus::Stopped,
                    description: "Control Godot Editor for game development".to_string(),
                },
            ],
        }
    }

    pub fn set_harness_status(&mut self, harness_id: &str, status: HarnessStatus) {
        if let Some(harness) = self.harnesses.iter_mut().find(|h| h.id == harness_id) {
            harness.status = status;
        }
    }

    pub fn add_harness(&mut self, info: HarnessInfo) {
        self.harnesses.push(info);
    }
}

impl Default for HarnessPanelWidget {
    fn default() -> Self {
        Self::new()
    }
}

impl Widget for HarnessPanelWidget {
    fn ui(&mut self, ui: &mut Ui) -> Result<Vec<WidgetEvent>> {
        for harness in &self.harnesses {
            ui.horizontal(|ui| {
                // Status indicator
                let status_color = harness.status.color();
                let (rect, _response) = ui.allocate_exact_size(
                    eframe::egui::Vec2::new(8.0, 8.0),
                    eframe::egui::Sense::hover(),
                );
                ui.painter().circle_filled(rect.center(), 4.0, status_color);
                
                ui.label(&harness.name);
                ui.with_layout(eframe::egui::Layout::right_to_left(eframe::egui::Align::Center), |ui| {
                    ui.colored_label(
                        eframe::egui::Color32::GRAY,
                        format!("({})", harness.status.label()),
                    );
                });
            });
        }
        
        Ok(vec![])
    }

    fn title(&self) -> String {
        "Harnesses".to_string()
    }

    fn id(&self) -> String {
        "harness_panel".to_string()
    }
}
